name: Build and Publish Blog

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install pandoc
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      # Convert Markdown → HTML
      - name: Build HTML
        run: |
          rm -rf docs
          mkdir -p docs/posts

          # Convert index.md → index.html
          pandoc index.md \
            --template=templates/page.html \
            -o docs/index.html

          # Convert each post
          for f in posts/*.md; do
            base=$(basename "$f" .md)
            pandoc "$f" \
              --template=templates/page.html \
              -o "docs/posts/$base.html"
          done

      # Auto-generate a listing page of posts
      - name: Generate post list
        run: |
          echo "# Blog Posts" > docs/posts/index.md
          echo "" >> docs/posts/index.md
          for f in posts/*.md; do
            base=$(basename "$f" .md)
            title=$(head -n 1 "$f" | sed 's/# //')
            echo "- [$title](./$base.html)" >> docs/posts/index.md
          done

          pandoc docs/posts/index.md \
            --template=templates/page.html \
            -o docs/posts/index.html

      # Commit the generated site back to docs/
      - name: Commit and push generated site
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs
          git commit -m "Rebuild site" || echo "No changes"
          git push
